spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/chaekdam
    username: root
    password: password
  data:
    redis:
      host: redis
      port: 6379
      password: password
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
jwt:
  secret:
    key: youcantrevealtheaccesssecretkey123459876
image:
  path: /app/assets/images/
aladin:
  ttb-key: ttbMrhappyjs1948005