spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/chaekdam
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: 20010203
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
jwt:
  secret:
    key: youcantrevealtheaccesssecretkey123459876
image:
  path: /home/ubuntu/images/
kakao:
  rest-api-key: ddef038fa084012b787cdc2e0ac14a40
aladin:
  ttb-key: ttbMrhappyjs1948005