spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/baram
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: 20010203
  servlet:
    multipart:
      enabled: true
jwt:
  secret:
    key: youcantrevealtheaccesssecretkey123459876
image:
  path: /Users/yangts/Documents/imgs/